/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mateofr.tareaevaluacion.gui.companyas;

import com.mateofr.tareaevaluacion.logicanegocio.Logica;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateo
 */
public class GestorCompanyas extends javax.swing.JFrame {

    private final Logica logica = new Logica();
    private static AltaCompanyas ac;
    private static ModificarCompanyas mc;
    private static BajaCompanyas bc;
    private static ConsultaCompanyas cc;

    /**
     * Creates new form GestorCompanyas
     */
    public GestorCompanyas() {
        initComponents();
        logica.ponLaAyudaFrame(itmAyuda1, "gestor_companyas",this);

    }

    public void ponLaAyuda(JMenuItem AyudaItem, String pantalla) {
        try {
            File fichero = new File("help" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            hb.enableHelpOnButton(AyudaItem, pantalla, helpset);

        } catch (IllegalArgumentException | MalformedURLException | HelpSetException e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error al mostrar la ayuda", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAltaCompanyas = new javax.swing.JButton();
        btnModCompanyas = new javax.swing.JButton();
        btnConsultaCompanyas = new javax.swing.JButton();
        btnBajaCompanyas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmAyuda1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTOR DE COMPAÑÍAS");

        jPanel1.setNextFocusableComponent(jLabel1);
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        btnAltaCompanyas.setBackground(new java.awt.Color(255, 102, 102));
        btnAltaCompanyas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAltaCompanyas.setText("ALTA DE COMPAÑÍAS");
        btnAltaCompanyas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAltaCompanyas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaCompanyasActionPerformed(evt);
            }
        });

        btnModCompanyas.setBackground(new java.awt.Color(255, 102, 102));
        btnModCompanyas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModCompanyas.setText("MODIFICACIÓN DE COMPAÑÍAS");
        btnModCompanyas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModCompanyas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCompanyasActionPerformed(evt);
            }
        });

        btnConsultaCompanyas.setBackground(new java.awt.Color(255, 102, 102));
        btnConsultaCompanyas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultaCompanyas.setText("CONSULTA DE COMPAÑÍAS");
        btnConsultaCompanyas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultaCompanyas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCompanyasActionPerformed(evt);
            }
        });

        btnBajaCompanyas.setBackground(new java.awt.Color(255, 102, 102));
        btnBajaCompanyas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBajaCompanyas.setText("BAJA DE COMPAÑÍAS");
        btnBajaCompanyas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBajaCompanyas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaCompanyasActionPerformed(evt);
            }
        });

        jMenu1.setText("Ayuda");

        itmAyuda1.setText("Mostrar Ayuda");
        itmAyuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAyuda1ActionPerformed(evt);
            }
        });
        jMenu1.add(itmAyuda1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(778, 778, 778))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultaCompanyas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(btnAltaCompanyas, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModCompanyas, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(btnBajaCompanyas, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAltaCompanyas, btnBajaCompanyas, btnConsultaCompanyas, btnModCompanyas});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaCompanyas, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnBajaCompanyas, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModCompanyas, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(btnConsultaCompanyas, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAltaCompanyas, btnBajaCompanyas, btnConsultaCompanyas, btnModCompanyas});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaCompanyasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaCompanyasActionPerformed
        if (ac == null) {
            ac = new AltaCompanyas();
        }
        ac.setVisible(true);
        

    }//GEN-LAST:event_btnAltaCompanyasActionPerformed

    private void btnModCompanyasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCompanyasActionPerformed
        if (mc == null) {
            mc = new ModificarCompanyas(null, false);
        }
        mc.setVisible(true);
        mc.actualizarComboBox();
    }//GEN-LAST:event_btnModCompanyasActionPerformed

    private void btnConsultaCompanyasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCompanyasActionPerformed
        if (cc == null) {
            cc = new ConsultaCompanyas(null, false);
        }
        cc.setVisible(true);
        cc.actualizarTabla();
    }//GEN-LAST:event_btnConsultaCompanyasActionPerformed

    private void btnBajaCompanyasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaCompanyasActionPerformed
        if (bc == null) {
            bc = new BajaCompanyas(null, false);
        }
        bc.setVisible(true);
        bc.actualizarComboBox();
        
    }//GEN-LAST:event_btnBajaCompanyasActionPerformed

    private void itmAyuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAyuda1ActionPerformed

    }//GEN-LAST:event_itmAyuda1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaCompanyas;
    private javax.swing.JButton btnBajaCompanyas;
    private javax.swing.JButton btnConsultaCompanyas;
    private javax.swing.JButton btnModCompanyas;
    private javax.swing.JMenuItem itmAyuda1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
